// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>Strive - Your Personal Activity Tracker</title><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css\"></head><body><header><nav><ul><li><a href=\"/\">Home</a></li><li><a href=\"/activities\">Activities</a></li></ul></nav></header><main><section id=\"welcome\"><h1>Welcome to Strive</h1><p>Your personal space for tracking sports activities.</p></section><section id=\"recent-activities\"><h2>Recent Activities</h2><div class=\"activity-feed\"><!-- This is where your activity summaries will go --><!-- Example of an activity summary --><div class=\"activity\"><img src=\"path/to/activity-thumbnail.jpg\" alt=\"Activity Thumbnail\"><div class=\"activity-info\"><h3>Evening Run</h3><p>Distance: 5km</p><p>Time: 30min</p><p>Pace: 6min/km</p></div></div><!-- Repeat for other activities --></div></section></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
